### ISSUE TITLE
Add ember-cli-htmlbars-inline-precompile to the list of Build-time Addons

### ISSUE THREAD

**Issue by andreyfel** [salsify/ember-cli-dependency-lint#12]
`ember-cli-htmlbars-inline-precompile` should be added to the list of exceptions by default.

**Comment by dfreeman** [comment]
@andreyfel What addons ship with a runtime dependency on `ember-cli-htmlbars-inline-precompile`? I'd expect that to be pretty unusual...

**Comment by andreyfel** [comment]
ember-test-helpers depend on it

**Comment by dfreeman** [comment]
Interesting, we've never run into a conflict on that before. I'd be happy to merge a PR that adds it to the default exceptions.

**Comment by dfreeman** [comment]
Fixed by #13
